[package]
name = "crudkit-web-macros"
version = "0.1.0"
edition = "2024"
autotests = false

[lib]
proc-macro = true

[[test]]
name = "tests"
path = "tests/progress.rs"

[dependencies]
crudkit-core-macros = { path = "../../../crudkit-core/crates/crudkit-core-macros" }

darling = { workspace = true }
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
crudkit-web = { path = "../crudkit-web" }
serde = "1.0.171"
trybuild = { version = "1.0.81", features = ["diff"] }
