[package]
name = "crudkit-validation"
version = "0.1.0"
edition = "2024"

[dependencies]
crudkit-resource = { path = "../crudkit-resource" }
crudkit-id = { path = "../crudkit-id" }
serde = { version = "1.0.228", features = ["derive"] }

[dev-dependencies]
assertr = "0.4.3"
serde_json = "1.0.149"
