[package]
name = "crudkit-derive-core"
version = "0.1.0"
edition = "2024"
description = "Shared utilities for crudkit derive macros"

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
