[package]
name = "derive-field"
version = "0.0.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
crudkit-derive-core = { path = "../../../crudkit-core/crates/crudkit-derive-core" }
crudkit-core = { path = "../../../crudkit-core/crates/crudkit-core" }
types = { path = "../types" }

darling = { workspace = true }
proc-macro-error = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
