[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/crudkit-core"]

[workspace.dependencies]
darling = "0.23.0"
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.104"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["extra-traits"] }
